version: "3"
services:
  web:
    container_name: django_server
    build: .
    image: docker_django_image
    environment:
       DEBUG: 'true'
       REDIS_HOST: 'redis'
       REDIS_PORT: 6379
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:

